controller_manager:
  ros__parameters:
    update_rate: 500 # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    impedance_controller:
      type: reach_controllers/ImpedanceController

impedance_controller:
  ros__parameters:
    joints:
      - axis_a
      - axis_b
      - axis_c
      - axis_d
      - axis_e
      - axis_f
      - axis_g

    friction:
      - 0.079 # axis_a
      - 0.079 # axis_b
      - 0.079 # axis_c
      - 0.079 # axis_d
      - 0.079 # axis_e
      - 0.079 # axis_f
      - 0.079 # axis_g

    gains:
      axis_a:
        stiffness: 30.0
        damping: 30.0

      axis_b:
        stiffness: 30.0
        damping: 30.0

      axis_c:
        stiffness: 30.0
        damping: 30.0

      axis_d:
        stiffness: 30.0
        damping: 30.0

      axis_e:
        stiffness: 30.0
        damping: 30.0

      axis_f:
        stiffness: 30.0
        damping: 30.0

      axis_g:
        stiffness: 30.0
        damping: 30.0
