joint_limits:
  axis_e:
    max_position: 6.10
    min_position: 0.0
  axis_d:
    max_position: 3.49
    min_position: -3.49
  axis_c:
    max_position: 3.22
    min_position: 0.0
  axis_b:
    max_position: 3.22
    min_position: 0.0
  axis_a:
    max_position: 0.015
    min_position: 0.0
